import { Inter, Manrope } from "next/font/google";
import "./globals.css";
// import { ReduxProvider } from "./redux/provider";
// import { store } from "./redux/store";

// const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        {/* <ReduxProvider store={store}> */}
        {children}
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}
